#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from enthrift.Thrift import TType, TMessageType, TException, TApplicationException

from enthrift.transport import TTransport
from enthrift.protocol import TBinaryProtocol, TProtocol
try:
  from enthrift.protocol import fastbinary
except:
  fastbinary = None


