#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from enthrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

EDAM_VERSION_MAJOR = 1
EDAM_VERSION_MINOR = 28
